[package]
name = "simple-audio-decoder-rs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib", "lib"]

[dependencies]
libc = "0.2.153"
once_cell = "1.19.0"
rodio = "0.17.3"
rubato = "0.15.0"
