[package]
name = "simple-audio-decoder-rs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
lazy_static = "1.4.0"
libc = "0.2.153"
rodio = "0.17.3"
rubato = "0.15.0"
